### ISSUE TITLE
Bug: Multitracker with more than two trackers creates separate entries

### ISSUE THREAD

**Issue by Jackymancs4** [open-nomie/nomie#106]
Hello @brandoncorbin 

Sorry in advance if I'm getting things wrong, but when I have a multitracker set as `#test1 #test2 #test3` and use it, I end up with three separate entries in history, equal to `#multitracker #test1` + `#test2` + `#test3` instead of one single entry as I expected (comparable to writing `#multitracker #test1 #test2 #test3`)

This is my test setup:

|Trackers|Multitracker Test|Result|Expected|
|---|---|---|---|
|![IMG_4724](https://user-images.githubusercontent.com/6209647/79469667-c152b600-8000-11ea-8371-7ede876a106a.png)|![IMG_4725](https://user-images.githubusercontent.com/6209647/79469674-c3b51000-8000-11ea-972c-f99853c8277f.png)|![IMG_4726](https://user-images.githubusercontent.com/6209647/79469679-c4e63d00-8000-11ea-951f-6e106e2f67b5.png)|![IMG_7119242B500F-1](https://user-images.githubusercontent.com/6209647/79470719-088d7680-8002-11ea-9b3a-f7cef2a75bbc.jpeg)|

The screens comes from Nomie 4, but also v5 is affected.

Thanks

**Comment by brandoncorbin** [comment]
When you tap the multi-tracker and it presents each of the individual "tracker input" are you hitting SAVE or the "+" icon?  Hitting Save will save that single tracker right then and there, hitting the plus will add it to the list. If that's the problem - then I'll work on making that flow clearer - as it's pretty muddy as it currently stands.

**Comment by brandoncorbin** [comment]
Going through this, I thought it was originally a bug - and helped me catch an issue. However, the more I thought about it, I think this might just be a bad UX issue.  

When going through each of the trackers in the multiple step - are you hitting the "Save" button, or the "Add +" button?

Hitting Save saves the log immediately, hitting +Add, will just add it to the note field, then you can group them all together.  This UX is confusing, and will be fixed in an upcoming release.
