### ISSUE TITLE
Apple Healthkit/Google Fit access

### ISSUE THREAD

**Issue by sammosna** [open-nomie/nomie#13]
It would be great to integrate Apple Healthkit. For example for sleep, food, sexual activities.

**Comment by brandoncorbin** [comment]
I'm still trying to figure out what's going to be the best way to get data into Nomie 4. Nomie 3 had calendar importing, Nomie 2 had the API.  But since it's a PWA, it's not going to have direct access to low level phone data.  

Currently the only way to push data into Nomie 4 is using the URL parameter note, for example: https://open.nomie.app/?note=URI_ENCODED_NOTE 

The note can contain anything, including tracker data like: #mood(4) #heartrate(77.34) - but it must be encoded.

**Comment by blankster** [comment]
An API like Nomie v2. would be very great. To get the health data, I would use http://developer.exist.io what offers quite a lot data over their free (for subscribers) API.

_Side note: In Exists forum one of the owners is currently searching for the best habit tracking solution. That could be maybe a chance for you (and a win:win for everyone)._

**Comment by brandoncorbin** [comment]
The Nomie API is now available and can be used to import data. https://nomie.app/blog/01-nomie-4-1-30-release
