### ISSUE TITLE
Settings: "null" displayed instead of Account-Name and/or -ID

### ISSUE THREAD

**Issue by blankster** [open-nomie/nomie#15]
In the settings menu, the first entry looks like this with my account:
![image](https://user-images.githubusercontent.com/1443109/62428249-c6383980-b6ff-11e9-9775-035ee6972aca.png)

I guess that's a small mistake and it should display the account name and/or id.

**Comment by brandoncorbin** [comment]
logged in with Blockstack? Or are you using Local?

**Comment by blankster** [comment]
I'm logged in with Blockstack (Windows 10, Chrome - both latest versions). Please let me know what more debug information I can provide to help you to fix this problem.

_Blockstack is another piece of interesting technology - congrats for being that progressive (also back then with CouchDB)_

**Comment by huberf** [comment]
I experienced this but it wasn't a Nomie issue. In the Blockstack account selection UI, instead of showing my username it showed a hash (this was the second computer I had logged into Blockstack). When I logged into Nomie using this, it must not have known my username and thus only provided an account hash. I resolved it by signing out and back in. Blockstack then correctly displayed my user name rather than the hash and Nomie was then able to pick it up. It seems possible that it is an issue on Blockstack's side, but one that maybe the Nomie UI can make clearer.

**Comment by blankster** [comment]
I've to smile, again the "usual suspects" - Hi Noah!

Thanks for providing more informaton. I've tried it right now from work where it worked as you said. At home, I see a hash, here I saw my Blockstack username and the "null" value is replaced by my Blockstack account id.

I'm not sure if it's a blockstack problem, as I'm experiencing a login not as real login - it triggers the recovery function where I first must provide the "secret code", then the password and finally the email-address again. Then I'm logged in.

I don't know from which side the bug occurs but I had this too with my first-login (when a hash was shown) from home (I've created the Blockstack account not over the Nomie sign-up/in process, I did it directly on Blockstack).
