### ISSUE TITLE
Tracker with named options

### ISSUE THREAD

**Issue by daniel-hermann** [open-nomie/nomie#23]
A tracker with named options would be great.

example:

tracker "meal":
* eating in
* eating out - budget
* eating out - splurge

or "going out":
* Cinema
* Bar
* ...

**Comment by brandoncorbin** [comment]
I have yet to be able to figure out the best way to handle a "list type" - mainly because the list options lack a value. Meaning, the way data is stored `#trackerTag(value)` doesn't exactly fit.

It's possible that each option could have its own tag - and the final log could be something like: `#meal #eat_in` or `#meal #eat_out`,  then we make it so stats can be generated for a tag that also has another tag specified.

**Comment by brandoncorbin** [comment]
I'm closing this, as I won't be adding it to Nomie 5. That being said - I think the Picker tracker type can solve this pretty nicely now
